import type { Metadata } from "next";
import "./globals.css";
import Header from "@/Components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-gradient-to-br from-purple-900 via-indigo-800 to-purple-500"
      >
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
